# Generated by dumpbrew.sh from brew list — 2026-07-18 17:30:18

# formulae (brew list --formula)
brew "fnm"
brew "pnpm"
brew "starship"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# casks (brew list --cask)
cask "claude-code"
cask "font-jetbrains-mono-nerd-font"
cask "ghostty"
cask "miaoyan"
cask "termius"
