#!/usr/bin/env bash
# 从 brew list 生成 Brewfile（仅 formula + cask，不含 vscode/mas 等）
# 用法: ./dumpbrew.sh [-o PATH] [--formula-only|--cask-only] [--force]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="${SCRIPT_DIR}/../Brewfile"
FORMULA=1
CASK=1
FORCE=0

usage() {
  echo "用法: $0 [-o PATH] [--formula-only|--cask-only] [--force]" >&2
  echo "  -o, --output PATH   输出文件（默认: 仓库根目录/Brewfile）" >&2
  echo "  --formula-only      仅导出 brew list --formula" >&2
  echo "  --cask-only         仅导出 brew list --cask" >&2
  echo "  --force, -f         目标已存在时覆盖" >&2
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -o|--output)
      [[ $# -ge 2 ]] || usage
      OUT="$2"
      shift 2
      ;;
    --formula-only) FORMULA=1; CASK=0; shift ;;
    --cask-only) FORMULA=0; CASK=1; shift ;;
    --force|-f) FORCE=1; shift ;;
    -h|--help) usage ;;
    *) echo "未知参数: $1" >&2; usage ;;
  esac
done

ensure_brew() {
  if command -v brew >/dev/null 2>&1; then
    return 0
  fi
  if [[ -x /opt/homebrew/bin/brew ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  elif [[ -x /usr/local/bin/brew ]]; then
    eval "$(/usr/local/bin/brew shellenv)"
  fi
  if ! command -v brew >/dev/null 2>&1; then
    echo "错误: 未找到 brew" >&2
    exit 1
  fi
}

ensure_brew

if [[ -e "$OUT" && "$FORCE" -ne 1 ]]; then
  echo "错误: 文件已存在: $OUT（使用 --force 覆盖）" >&2
  exit 1
fi

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  echo "# Generated by dumpbrew.sh from brew list — $(date '+%Y-%m-%d %H:%M:%S')"
  echo

  if [[ "$FORMULA" -eq 1 ]]; then
    echo "# formulae (brew list --formula)"
    brew list --formula | sort | while IFS= read -r name; do
      [[ -n "$name" ]] || continue
      printf 'brew "%s"\n' "$name"
    done
    echo
  fi

  if [[ "$CASK" -eq 1 ]]; then
    echo "# casks (brew list --cask)"
    brew list --cask | sort | while IFS= read -r name; do
      [[ -n "$name" ]] || continue
      printf 'cask "%s"\n' "$name"
    done
  fi
} >"$tmp"

mkdir -p "$(dirname "$OUT")"
mv "$tmp" "$OUT"
trap - EXIT

echo "已导出: $OUT"
echo "  formula: $(grep -c '^brew ' "$OUT" || true)"
echo "  cask:    $(grep -c '^cask ' "$OUT" || true)"
